import Head from "next/head";

import { Button } from "../components/Buttons/Default";

import styles from "../styles/pages/Auth.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>GS Express</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.pageAuth}>
        <aside>
          <img
            src="/assets/illustration.svg"
            alt="ilustração simbolizando perguntas e respostas"
            draggable={false}
          />
          <strong>Crie salas de Q&amp;A ao-vivo</strong>
          <p>Tire as dúvidas da sua audiência em tempo-real!</p>
        </aside>

        <main>
          <div className="main-content">
            <img draggable={false} src="/assets/logo.svg" alt="letmeask" />
            <button onClick={() => {}} className="create-room" type="button">
              Crie sua sala com o Google
            </button>
            <div className="separator">ou entre em uma outra sala</div>
            <form onSubmit={() => {}}>
              <input
                onChange={() => {}}
                id="room-code"
                placeholder="Digite o código da sala"
                type="text"
              />

              <Button type="submit">Entrar na sala</Button>
            </form>
          </div>
        </main>
      </div>
    </>
  );
}
