import Head from "next/head";
import { withSSRAuth } from "../utils/withSSRAuth";

import { Profile } from "../components/Profile";

import styles from "../styles/pages/Welcome.module.scss";

export default function welcome() {
  return (
    <>
      <Head>
        <title>Serviços | Genesis Express</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id={styles.welcomePage}>
        <div className={styles.cover}>
          <Profile />

          <main className={styles.content}>
            <a href="#">
              <img draggable={false} src="/assets/grow-up-point.png" alt="" />

              <div>
                <h3>Ponto de venda</h3>
                <p>Gere faturas através do ponto de venda</p>
              </div>
            </a>
            <a href="#">
              <img draggable={false} src="/assets/reports-service.png" alt="" />

              <div>
                <h3>Relatórios</h3>
                <p>Gerencie seus relatórios</p>
              </div>
            </a>
          </main>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = withSSRAuth(async (ctx) => {
  return { props: {} };
});
